In [ ]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.5'

In [4]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-29 15:10:14--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.008s

2026-09-29 15:10:14 (74.8 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [5]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [10]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [13]:
df.shape

(10000, 11)

In [15]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [20]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [25]:
asia_filter = df['origin'] == "Asia"
df[asia_filter]['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [45]:
# Q6
median_horsepower = df['horsepower'].median()
mode_horsepower = df['horsepower'].mode()

In [46]:
type(mode_horsepower), type(mode_horsepower[0])

(pandas.Series, numpy.float64)

In [41]:
median_horsepower, mode_horsepower

(np.float64(254.0), np.float64(252.0))

In [42]:
filled_horsepower = df['horsepower'].fillna(mode_horsepower)

In [43]:
filled_horsepower.median()

np.float64(252.0)

In [44]:
filled_horsepower.isna().sum()

np.int64(0)

In [ ]:
# Q7
# 1
asian_cars = df[asia_filter]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [51]:
# 2
asian_weight_year = asian_cars[["vehicle_weight", "model_year"]]

In [54]:
X = asian_weight_year[:7].values

In [55]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [59]:
XTX = X.T.dot(X)

In [66]:
import numpy as np

In [67]:
XTX_inverse = np.linalg.inv(XTX)

In [68]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [72]:
XTX_inverse.dot(X.T).dot(y).sum()

np.float64(0.36919696904925486)